### ISSUE TITLE
Zipkin trace lacks information regarding destiny server when communicating with non-Java services

### ISSUE THREAD

**Issue by embs** [microservices-demo/orders#48]
After cart checkout, the `orders` service traces interactions with `user`, `carts`, `payment` and `shipping` services. Spans regarding remote calls to the Java services (`carts` & `shipping`) seem complete. For instance:

![selection_004](https://user-images.githubusercontent.com/1200033/30330250-e5f02254-97aa-11e7-9a28-bae5f8ac5774.png)

But spans regarding calls to non-Java services don't present Service Receive and Service Send annotations. E.g.:

![selection_005](https://user-images.githubusercontent.com/1200033/30330467-8d385b4e-97ab-11e7-8aa9-71feddc67a4b.png)

I'm investigating how instrumentation is currently implemented in order to try enhancing the tracing with the missing info. Any advices about this will be appreciated.

_This issue relates to #32_

**Comment by jasonrichardsmith** [comment]
These instrumentations were just written as POCs.  We welcome and PRs in regards to their improvement.

**Comment by embs** [comment]
@jasonrichardsmith would you please review https://github.com/microservices-demo/user/pull/53?

**Comment by embs** [comment]
Closing in favor of https://github.com/microservices-demo/microservices-demo/issues/741
